version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/activations

  postgres:
    image: public.ecr.aws/docker/library/postgres:12.13
    restart: always
    volumes:
      - ./src/main/resources/db/docker-db-init.sql:/docker-entrypoint-initdb.d/docker-db-init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: activations
